name: Common CI
on:
  workflow_call:
    inputs:
      component_name:
        required: true
        type: string
      app_type:
        required: true
        type: string
jobs:
  Download-Dependencies-Docker-Build:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Download Dependencies
        run: |
          if [ ${{inputs.app_type}} == nodejs ]; then
            npm install
          elif [ ${{inputs.app_type}} == maven ]; then
            export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-17.0.14.0.7-2.el9.x86_64
            export PATH=$JAVA_HOME/bin:$PATH
            /usr/share/maven/bin/mvn package
          fi
          docker build -t 713881792245.dkr.ecr.us-east-1.amazonaws.com/${{inputs.component_name}}:${GITHUB_SHA} .


  Docker-Push:
    runs-on: self-hosted
    needs: Download-Dependencies-Docker-Build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Docker Push
        run: |
          export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 713881792245.dkr.ecr.us-east-1.amazonaws.com
          docker push 713881792245.dkr.ecr.us-east-1.amazonaws.com/${{inputs.component_name}}:${GITHUB_SHA}

  Dev-Deployment:
    runs-on: self-hosted
    needs: Docker-Push
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: vsaitejasgitorg/roboshop-helm
      - name: Deploy
        run: |
          export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
          #aws eks update-kubeconfig  --name dev
          #make component=${{ inputs.component_name }} env=dev

  QA-Deployment:
    runs-on: self-hosted
    needs: Dev-Deployment
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: vsaitejasgitorg/roboshop-helm
      - name: Deploy
        run: |
          export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
          #aws eks update-kubeconfig  --name dev
          #make component=${{ inputs.component_name }} env=qa

  UAT-Deployment:
    runs-on: self-hosted
    needs: QA-Deployment
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: vsaitejasgitorg/roboshop-helm
      - name: Deploy
        run: |
          export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
          #aws eks update-kubeconfig  --name dev
          #make component=${{ inputs.component_name }} env=uat

  PROD-Deployment:
    runs-on: self-hosted
    needs: UAT-Deployment
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: vsaitejasgitorg/roboshop-helm
      - name: Deploy
        run: |
          export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
          #aws eks update-kubeconfig  --name dev
          #make component=${{ inputs.component_name }} env=prod