name: Common CI
on:
  workflow_call:
    inputs:
      component_name:
        required: true
        type: string
      app_type:
        required: true
        type: string
jobs:
  Download-Dependencies-Docker-Build:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Download-Dependencies
        run: |
          if [ ${{inputs.app_type}} == nodejs ]; then
            npm install
          elif [ ${{inputs.app_type}} == maven ]; then
            mvn package
          fi
          docker build .


  Docker-Push:
    runs-on: self-hosted
    needs: Download-Dependencies-Docker-Build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Docker Build
        run: echo

  Dev-Deployment:
    runs-on: self-hosted
    needs: Docker-Push
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: vsaitejasgitorg/roboshop-helm
      - name: Deploy
        run: |
          export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
          #aws eks update-kubeconfig  --name dev
          #make component=${{ inputs.component_name }} env=dev

  QA-Deployment:
    runs-on: self-hosted
    needs: Dev-Deployment
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: vsaitejasgitorg/roboshop-helm
      - name: Deploy
        run: |
          export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
          #aws eks update-kubeconfig  --name dev
          #make component=${{ inputs.component_name }} env=qa

  UAT-Deployment:
    runs-on: self-hosted
    needs: QA-Deployment
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: vsaitejasgitorg/roboshop-helm
      - name: Deploy
        run: |
          export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
          #aws eks update-kubeconfig  --name dev
          #make component=${{ inputs.component_name }} env=uat

  PROD-Deployment:
    runs-on: self-hosted
    needs: UAT-Deployment
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: vsaitejasgitorg/roboshop-helm
      - name: Deploy
        run: |
          export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
          #aws eks update-kubeconfig  --name dev
          #make component=${{ inputs.component_name }} env=prod